### ISSUE TITLE
Short-term To-Do List

### ISSUE THREAD

**Issue by AlexStormwood** [BigfootDS/supercamo#3]
This is a new package that is meant to be a "rebuilt from the ground up" variant of a very fully-featured & stable package. So, it's gonna be missing some things for a bit until I catch up.

## Features 
- [ ] Let models declare a default value for properties and use those defaults in instance creation
- [ ] Add a URI option/alternative for connection, rather than just database name + folder path
- [ ] Make sure document references actually work 
- [ ] Make sure embedded documents actually work

## Wishful Thinking
- [ ] Allow for custom NedbClients, the same way that Documents get extended to create custom Documents
